<?php
// $Id$

/**
 * @file
 * Generate user assessment "quiz" for generating leads on your website.
 */

// ==========================
// = Implements hook_menu() =
// ==========================

function tm_assessment_menu() {
	$items['assessment/%'] = array(
		'title' => t('Assessment'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tm_assessment_form', 1),
		'access callback' => TRUE,
		'weight' => 1,
	);
	$items['assessment/%/info'] = array(
		'title' => t('Contact Information'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tm_assessment_form', 1),
		'access callback' => TRUE,
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 2,
	);
	$items['assessment/%/questions'] = array(
		'title' => t('Assessment Questions'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tm_assessment_form', 1),
		'access callback' => TRUE,
		'type' => MENU_LOCAL_TASK,
		'weight' => 3,
	);
	$items['assessment/%/results'] = array(
		'title' => t('Assessment Results'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tm_assessment_form', 1),
		'access callback' => TRUE,
		'type' => MENU_LOCAL_TASK,
		'weight' => 4,
	);
	return $items;
}

function tm_assessment_mypage() {
	return 'Hello World';
}

// =============================
// = Construct assessment form =
// =============================

function tm_assessment_form($form, &$form_state, $quiz_name) {
	$path = drupal_lookup_path('source', $quiz_name);
	$node = menu_get_object('node', 1, $path);
	$wrapper = entity_metadata_wrapper('node', $node);
	$question_text = $wrapper->field_question_collection[0]->field_question_text->value();
	dsm($node);
	
	$form['assessment_form'] = array(
		'#type' => 'horizontal_tabs',
	);
	$form['info_formset'] = array(
		'#type' => 'fieldset',
		'#title' => t('Info'),
		'#collapsible' => TRUE,
		'#group' => 'assessment_form',
	);
	$form['info_formset']['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Name'),
		'#group' => 'assessment_form',
	);
	$form['question_formset'] = array(
		'#type' => 'fieldset',
		'#title' => t('Assessment Questions'),
		'#colapsible' => TRUE,
		'#group' => 'assessment_form',
	);
	$form['question_formset']['question'] = array(
		'#type' => 'textfield',
		'#title' => $question_text,
		'#group' => 'assessment_form',
	);
	$form['#submit'][] = 'tm_assessment_form_submit';
	
	return $form;
}

// ===================================
// = assessment form submit callback =
// ===================================

function tm_assessment_form_submit($form, &$form_state) {
	//empty for now.
}